services:
  tts:
    build: .
    container_name: tts_webapp
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=production
      - TZ=America/Toronto  # Set timezone
      - VIRTUAL_HOST=tts.asamoahboateng.com
      - VIRTUAL_PORT=5000
    volumes:
      - .:/app
      - ../Logs/tts_logs:/app/logs
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true